### ISSUE TITLE
tree in /usr/local/bin overridden by bash tree function

### ISSUE THREAD

**Issue by gramtech** [reedia/dotfiles#8]
This is related to use of `tree`.

tree is installed as part of homebrew/brew-package.sh, however there is a function in .bash_profile that essentially overrides this.

I propose one of the following options, please let me you thoughts / objections.

1. remove the tree function in bash profile
2. if you want to keep it rename it to treee or btree
3. wrap the bash function in a check to see if /usr/local/bin/tree exists and either dont load the bash version or load it with a different name.
4. leave as is

**Comment by sebastienrousseau** [comment]
Yes fine with this

**Comment by gramtech** [comment]
ok I'll put something to gether and submit a pull request
